export default [
    {
        id: 1,
        name: 'Product 1',
        price: 10,
        image: 'https://via.placeholder.com/150',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elitconsectetur adipiscing elit. Nulla quis lorem ut libero malesuada feugiat.',
        category: 'Category 1',
        quantity: 10,
        inStock: true,
        featured: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
        deleted: false,
    },
    {
        id: 2,
        name: 'Product 2',
        price: 20,
        image: 'https://via.placeholder.com/150',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elitconsectetur adipiscing elit. Nulla quis lorem ut libero malesuada feugiat.',
        category: 'Category 2',
        quantity: 20,
        inStock: true,
        featured: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
        deleted: false,
    },
    {
        id: 3,
        name: 'Product 2',
        price: 20,
        image: 'https://via.placeholder.com/150',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elitconsectetur adipiscing elit. Nulla quis lorem ut libero malesuada feugiat.',
        category: 'Category 2',
        quantity: 20,
        inStock: true,
        featured: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
        deleted: false,
    },
    {
        id: 4,
        name: 'Product 2',
        price: 20,
        image: 'https://via.placeholder.com/150',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elitconsectetur adipiscing elit. Nulla quis lorem ut libero malesuada feugiat.',
        category: 'Category 2',
        quantity: 20,
        inStock: true,
        featured: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
        deleted: false,
    },
    {
        id: 5,
        name: 'Product 2',
        price: 20,
        image: 'https://via.placeholder.com/150',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elitconsectetur adipiscing elit. Nulla quis lorem ut libero malesuada feugiat.',
        category: 'Category 2',
        quantity: 20,
        inStock: true,
        featured: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
        deleted: false,
    },
    {
        id: 6,
        name: 'Product 2',
        price: 20,
        image: 'https://via.placeholder.com/150',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elitconsectetur adipiscing elit. Nulla quis lorem ut libero malesuada feugiat.',
        category: 'Category 2',
        quantity: 20,
        inStock: true,
        featured: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
        deleted: false,
    },
    {
        id: 7,
        name: 'Product 2',
        price: 20,
        image: 'https://via.placeholder.com/150',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elitconsectetur adipiscing elit. Nulla quis lorem ut libero malesuada feugiat.',
        category: 'Category 2',
        quantity: 20,
        inStock: true,
        featured: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
        deleted: false,
    },
    {
        id: 8,
        name: 'Product 2',
        price: 20,
        image: 'https://via.placeholder.com/150',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elitconsectetur adipiscing elit. Nulla quis lorem ut libero malesuada feugiat.',
        category: 'Category 2',
        quantity: 20,
        inStock: true,
        featured: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
        deleted: false,
    },
    {
        id: 9,
        name: 'Product 2',
        price: 20,
        image: 'https://via.placeholder.com/150',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elitconsectetur adipiscing elit. Nulla quis lorem ut libero malesuada feugiat.',
        category: 'Category 2',
        quantity: 20,
        inStock: true,
        featured: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
        deleted: false,
    },
    {
        id: 10,
        name: 'Product 2',
        price: 20,
        image: 'https://via.placeholder.com/150',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elitconsectetur adipiscing elit. Nulla quis lorem ut libero malesuada feugiat.',
        category: 'Category 2',
        quantity: 20,
        inStock: true,
        featured: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
        deleted: false,
    },
]